SELECT DISTINCT
    t.id AS textbook_id,
    -- t.title,
    first_value(x.subject) OVER (PARTITION BY t.id ORDER BY x.order_num) AS subject,
    first_value(x.subject_group) OVER (PARTITION BY t.id ORDER BY x.order_num) AS subject_group
FROM
    solutions_textbook t
    LEFT JOIN solutions_textbook_subjects tsubs ON tsubs.textbook_id = t.id
    LEFT JOIN subjects_subject sub ON sub.id = tsubs.subject_id
    LEFT JOIN ((
        VALUES 
        ('play', 'Humanities', 1),
        ('poem', 'Humanities', 2),
        ('film', 'Art', 3),
        ('movies', 'Art', 4),
        ('autobiography', 'Literature', 5),
        ('short story', 'Art', 6),
        ('novel', 'Literature', 7),
        ('art', 'Art', 8),
        ('elementary education', 'Education', 9),
        ('education', 'Education', 10),
        ('criminal law', 'Law', 11),
        ('administrative law', 'Law', 12),
        ('civil law', 'Law', 13),
        ('comparative law', 'Law', 14),
        ('civics', 'Social Science', 15),
        ('Political Science', 'Social Science', 16),
        ('ethics', 'Philosophy', 17),
        ('neuroscience', 'Science', 18),
        ('immunology', 'Science', 19),
        ('cardiology', 'Medicine', 20),
        ('pathology', 'Medicine', 21),
        ('psychiatry', 'Medicine', 22),
        ('anatomy and physiology', 'Medicine', 23),
        ('genetics', 'Biology', 24),
        ('optometry', 'Medicine', 25),
        ('nutrition', 'Health', 26),
        ('public health', 'Health', 27),
        ('health', 'Health', 28),
        ('accounting', 'Business', 29),
        ('econometrics', 'Economics', 30),
        ('managerial economics', 'Economics', 31),
        ('macroeconomics', 'Economics', 32),
        ('microeconomics', 'Economics', 33),
        ('finance', 'Business', 34),
        ('international economics', 'Economics', 35),
        ('marketing', 'Business', 36),
        ('advertising', 'Business', 37),
        ('management', 'Business', 38),
        ('business', 'Business', 39),
        ('US government', 'Political Science', 40),
        ('biological anthropology', 'Anthropology', 41),
        ('anthropology', 'Anthropology', 42),
        ('sociology', 'Social Science', 43),
        ('abnormal psychology', 'Psychology', 44),
        ('cognitive psychology', 'Psychology', 45),
        ('biological psychology', 'Psychology', 46),
        ('psychology', 'Psychology', 47),
        ('linguistics', 'Humanities', 48),
        ('literature', 'Humanities', 49),
        ('literature and english', 'Humanities', 50),
        ('english', 'Language', 51),
        ('music theory', 'Music', 52),
        ('music', 'Music', 53),
        ('scientific history', 'History', 54),
        ('US history', 'History', 55),
        ('european history', 'History', 56),
        ('modern history', 'History', 57),
        ('ancient history', 'History', 58),
        ('world history', 'History', 59),
        ('spanish', 'Language', 60),
        ('french', 'Language', 61),
        ('german', 'Language', 62),
        ('latin', 'Language', 63),
        ('foreign languages', 'Language', 64),
        ('geology', 'Geology', 65),
        ('geography of north america', 'Geography', 66),
        ('geography', 'Geography', 67),
        ('social sciences', 'Social Science', 68),
        ('life science', 'Biology', 69),
        ('biotechnology', 'Science', 70),
        ('civil engineering', 'Engineering', 71),
        ('materials science', 'Engineering', 72),
        ('electrical engineering', 'Engineering', 73),
        ('mechanical engineering', 'Engineering', 74),
        ('software engineering', 'Computer Science', 75),
        ('computer architecture', 'Computer Science', 76),
        ('engineering', 'Engineering', 77),
        ('ecology', 'Environmental Science', 78),
        ('animal science', 'Biology', 79),
        ('environmental science', 'Environmental Science', 80),
        ('astronomy', 'Science', 81),
        ('inorganic chemistry', 'Chemistry', 82),
        ('organic chemistry', 'Chemistry', 83),
        ('chemistry', 'Chemistry', 84),
        ('marine biology', 'Biology', 85),
        ('microbiology', 'Biology', 86),
        ('molecular biology', 'Biology', 87),
        ('cell biology', 'Biology', 88),
        ('human biology', 'Biology', 89),
        ('biology', 'Biology', 90),
        ('physics', 'Physics', 91),
        ('oceanography', 'Science', 92),
        ('physical science', 'Science', 93),
        ('sports', 'Sports', 94),
        ('earth science', 'Geology', 95),
        ('computer science', 'Computer Science', 96),
        ('economics', 'Economics', 97),
        ('abstract algebra', 'Mathematics', 98),
        ('complex variables', 'Mathematics', 99),
        ('differential equations', 'Mathematics', 100),
        ('linear algebra', 'Mathematics', 101),
        ('statistics', 'Mathematics', 102),
        ('probability', 'Mathematics', 103),
        ('calculus', 'Mathematics', 104),
        ('discrete math', 'Mathematics', 105),
        ('finite math', 'Mathematics', 106),
        ('analysis', 'Mathematics', 107),
        ('college algebra', 'Mathematics', 108),
        ('precalculus', 'Mathematics', 109),
        ('algebra 2', 'Mathematics', 110),
        ('geometry', 'Mathematics', 111),
        ('algebra', 'Mathematics', 112),
        ('integrated math', 'Mathematics', 113),
        ('trigonometry', 'Mathematics', 114),
        ('business math', 'Business', 115),
        ('pre-algebra', 'Mathematics', 116),
        ('advanced mathematics', 'Mathematics', 117),
        ('math foundations', 'Mathematics', 118),
        ('high school math', 'Education', 119),
        ('upper level math', 'Mathematics', 120),
        ('vocabulary', 'Language', 121),
        ('critical reading', 'Humanities', 122),
        ('humanities', 'Humanities', 123),
        ('business studies', 'Business', 124),
        ('AP', 'Education', 125),
        ('IB', 'Education', 126),
        ('SAT', 'Education', 127),
        ('A Level', 'Education', 128),
        ('vocational', 'Vocational', 129),
        ('history', 'History', 130),
        ('science', 'Science', 131),
        ('math', 'Mathematics', 132),
        ('animals', 'Biology', 133),
        ('more languages', 'Language', 134),
        ('fun', 'Entertainment', 135),
        ('College Prep', 'Education', 136),
        ('Solving Equations', 'Mathematics', 137),
        ('other', 'Miscellaneous', 138),
        ('more', 'Miscellaneous', 139)
    )) AS x(subject, subject_group, order_num) ON x.subject = sub.name
WHERE
    t.is_master
    AND t.isbn ILIKE '978%%';
